config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'diners#index'
  resources :diners, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :reviews, only: [:edit, :update]

end

app/models/diner.rb
class Diner < ActiveRecord::Base
  belongs_to :user

  has_many :reviews
  validates :name, presence: true
  validates :address, presence: true
  validates :user, presence: true 
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :diner
  belongs_to :user

  validates :rating, presence: true, numericality:
    { only_integer: true,
      greater_than_or_equal_to: 1,
      less_than_or_equal_to: 5,
      message: "must be between 1 and 5"
  }
  validates :body, presence: true
  validates :user_id, presence: true
  validates :diner_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :diners
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :first_name, presence: true
  validates :last_name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
    end

    def authenticate_user
      if !user_signed_in?
        raise_error
      end
    end

    def raise_error
      raise ActionController::RoutingError.new("Not Found")
    end
end

app/controllers/diners_controller.rb
class DinersController < ApplicationController

  def new
    @diner = Diner.new
  end

  def index
    @diners = Diner.all
  end

  def create
    @diner = Diner.new(diner_params)
    @diner.user = current_user
    if @diner.save
      flash[:notice] = "Diner added succesfully!"
      redirect_to diner_path(@diner)
    else
      flash[:errors] = @diner.errors.full_messages.join(". ")
      render :new
    end
  end

  def show
    @diner = Diner.find(params[:id])
    @reviews = @diner.reviews
  end

  def edit
    @diner = Diner.find(params[:id])
  end

  def update
    @diner = Diner.find(params[:id])
    if @diner.update_attributes(diner_params)
      redirect_to diner_path(@diner)
    else
      render :edit
    end
  end

  def destroy
    @diners = Diner.all.order(created_at: :desc)
    @diner = Diner.find(params[:id])
    @diner.destroy

    redirect_to diners_path
  end

  private
  def diner_params
    params.require(:diner).permit(:name, :address, :description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user, except [:index, :show]
  
  def new
    @diner = Diner.find(params[:diner_id])
    @review = Review.new
  end

  def create
    @diner = Diner.find(params[:diner_id])
    @review = @diner.reviews.new(review_params)
    @review.user = current_user

    if @review.save
      flash[:notice] = "Opinion noted!"
      redirect_to diner_path(@diner)
    else
      flash[:errors] = @review.errors.full_messages.join(". ")
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
    @review.diner = @diner
  end

  def update
    @review = Review.find(params[:id])
    if @review.update_attributes(review_params)
      redirect_to diner_path(@review.diner)
    else
      render :edit
    end
  end

  def destroy
    @diner = Diner.find(params[:diner_id])
    Review.find(params[:id]).destroy

    redirect_to diner_path(@diner)
  end

  private
  def review_params
    params.require(:review).permit(:rating, :body, :diner_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/diners/edit.html.erb
<div class="page-background">
  <h1>Edit Diner Info</h1>

  <%= form_for(@diner) do |f| %>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.label :name %>
        <%= f.text_field :name %>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.label :address %>
        <%= f.text_field :address %>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.label :description %>
        <%= f.text_field :description %>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.submit "Submit", :class => 'button'%>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="medium-12 columns">
      <ul class="button-group even-3">
        <%= link_to "Back to All", diners_path, :class => "button" %>
      </ul>
    </div>
  </div>
</div>

app/views/diners/index.html.erb
<html>
<head>
  <title>Beantown Starch</title>
  <%= javascript_include_tag "application" %>
</head>

<body>
  <div class="fixed">
    <div class="nav-bar">
      <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
            <h1><a href="#">Beantown Starch: A Home Fries Review Site</a></h1>
          </li>
        </ul>

        <section class="top-bar-section">
          <ul class="right">
            <% if user_signed_in? %>
            <li class="form-link">
              <%= link_to "Add New Diner", new_diner_path %>
            </li>
          </ul>
          <ul class="left">
            <li class="form-link">
              <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
            </li>
            <% else %>
            <li class="form-link">
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
            <li class="form-link">
              <%= link_to "Sign In", new_user_session_path %>
            </li>
            <% end %>
          </ul>
        </section>
      </nav>
    </div>
  </div>

    <ul>
      <% @diners.each do |diner| %>
        <div class="columns medium-3 offset-2">
          <div class="diner">
            View Home Fries Rating for <strong><%= link_to diner.name, diner_path(diner) %></strong>
            <!-- <img src="http://media.nj.com/the_dish/photo/diner-home-friesjpg-5efdc3b03d38279d_large.jpg"> -->
          </div>
        </div>
      <% end %>
    </ul>

</body>

app/views/diners/new.html.erb
<div class="page-background">
  <h1>Add a Diner</h1>

  <%= form_for(@diner) do |f| %>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.label :name %>
        <%= f.text_field :name %>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.label :address %>
        <%= f.text_field :address %>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.label :description %>
        <%= f.text_field :description %>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.submit "Submit", :class => 'button'%>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="medium-12 columns">
      <ul class="button-group even-3">
        <%= link_to "Back to All", diners_path, :class => "button" %>
      </ul>
    </div>
  </div>
</div>

app/views/diners/show.html.erb
<div class="page-background">
  <h1><%= @diner.name %></h1>

  <p class="address"><i><%= @diner.address %></i></p>

  <%if @diner.description.empty? %>
    <div class="row">
      <div class="medium-6 small-centered columns">
        <div class="header panel">This description is empty. Tell us what you know!</div>
    </div>
  <% else %>
    <div class="row">
      <div class="medium-6 small-centered columns">
        <div class="header panel"><%= @diner.description %></div>
    </div>
  <% end %>

  <div class="row">
    <div class="medium-6 large-centered columns">
      <ul class="button-group even-3">
        <%= link_to "How Are Their Home Fries?", new_diner_review_path(@diner), :class => "button" %>
        <%= link_to "Back to All", diners_path, :class => "button" %>
        <% if user_signed_in? && @diner.user == current_user %>
        <%= link_to "Edit Diner Info", edit_diner_path, :class => "button" %>
        <%= link_to "Delete Entry", diner_path(@diner), :class => "button",
          method: :delete,
          data: {confirm: "Are you sure you want to delete this entry?" } %>
        <% end %>
      </ul>
    </div>
  </div>

  <% @reviews.each do |review| %>
      <div class="review">
        <p><strong>Review date:</strong> <%= review.created_at.strftime("%B %d %Y") %></p>
        <p><strong>Reviewer:</strong> <%= review.user.first_name %></p>
        <p><strong>Rating:</strong> <%= review.rating %></p>
        <p><strong>Comments:</strong> <%= review.body %></p>
        <% if user_signed_in? && review.user == current_user %>
        <p><%= link_to "Edit Review", edit_review_path(review), :class => "button" %></p>
        <p><%= link_to "Delete Review", diner_review_path(@diner, @review), method: :delete, :class => "button" %></p>
        <% end %>
      </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Beantown Starch" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= value %>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/reviews/edit.html.erb
<div class="page-background">
  <h1>Edit Your Review!</h1>

  <%= form_for(@review) do |f| %>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.label :rating %>
        <%= f.text_field :rating %>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.label :body, "Review" %>
        <%= f.text_field :body %>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.submit "Submit", :class => 'button' %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="medium-12 columns">
      <ul class="button-group even-3">
        <%= link_to "Back to All", diners_path, :class => "button" %>
      </ul>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="page-background"
  <h1>Review the <%= @diner.name %>'s Home Fries!</h1>

  <%= form_for [@diner, @review] do |f| %>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.label :rating %>
        <%= f.text_field :rating %>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.label :body, "Review" %>
        <%= f.text_field :body %>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <%= f.submit "Submit", :class => 'button' %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="medium-12 columns">
      <ul class="button-group even-3">
        <%= link_to "Back to All", diners_path, :class => "button" %>
      </ul>
    </div>
  </div>
</div>